name: Deploy Lunatic Items

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # On indique à l'Action où se trouve le fichier package-lock.json
          cache-dependency-path: './Items/package-lock.json'

      - name: Install dependencies
        run: cd Items && npm install

      - name: Build project
        run: cd Items && npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # On pointe sur le dossier dist à l'intérieur de Items
          path: './Items/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4